name: spoiler_widget
description: A Flutter package to create spoiler animations similar to the one used in Telegram, allowing you to hide sensitive or spoiler-filled content until it's tapped or clicked.
version: 1.0.23
homepage: https://github.com/zhukeev/spoiler_widget
issue_tracker: https://github.com/zhukeev/spoiler_widget/issues

screenshots:
  - description: 'Spoiler Widget Demo'
    path: assets/spoiler_widget.jpg

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.27.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
    
topics: 
  - spoiler
  - text
  - particle
  - hidden
  - hide

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/particles.frag
    - shaders/bokeh_cover.frag
    - shaders/liquid_metal.frag
    - shaders/glitch_stripes.frag
    - shaders/mosaic_censor.frag
    - shaders/liquid_spectrum.frag
